# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigurePutToLightOperationBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lane_ids': 'list[str]',
        'side': 'str',
        'enable_put_to_light_validation': 'bool'
    }

    attribute_map = {
        'lane_ids': 'laneIds',
        'side': 'side',
        'enable_put_to_light_validation': 'enablePutToLightValidation'
    }

    def __init__(self, lane_ids=None, side=None, enable_put_to_light_validation=None):  # noqa: E501
        """ConfigurePutToLightOperationBody - a model defined in Swagger"""  # noqa: E501
        self._lane_ids = None
        self._side = None
        self._enable_put_to_light_validation = None
        self.discriminator = None
        self.lane_ids = lane_ids
        self.side = side
        if enable_put_to_light_validation is not None:
            self.enable_put_to_light_validation = enable_put_to_light_validation

    @property
    def lane_ids(self):
        """Gets the lane_ids of this ConfigurePutToLightOperationBody.  # noqa: E501

        The Lane's id's.  # noqa: E501

        :return: The lane_ids of this ConfigurePutToLightOperationBody.  # noqa: E501
        :rtype: list[str]
        """
        return self._lane_ids

    @lane_ids.setter
    def lane_ids(self, lane_ids):
        """Sets the lane_ids of this ConfigurePutToLightOperationBody.

        The Lane's id's.  # noqa: E501

        :param lane_ids: The lane_ids of this ConfigurePutToLightOperationBody.  # noqa: E501
        :type: list[str]
        """
        if lane_ids is None:
            raise ValueError("Invalid value for `lane_ids`, must not be `None`")  # noqa: E501

        self._lane_ids = lane_ids

    @property
    def side(self):
        """Gets the side of this ConfigurePutToLightOperationBody.  # noqa: E501

        The side of the Lanes.  # noqa: E501

        :return: The side of this ConfigurePutToLightOperationBody.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this ConfigurePutToLightOperationBody.

        The side of the Lanes.  # noqa: E501

        :param side: The side of this ConfigurePutToLightOperationBody.  # noqa: E501
        :type: str
        """
        if side is None:
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501
        allowed_values = ["UNKNOWN", "PRIMARY", "SECONDARY"]  # noqa: E501
        if side not in allowed_values:
            raise ValueError(
                "Invalid value for `side` ({0}), must be one of {1}"  # noqa: E501
                .format(side, allowed_values)
            )

        self._side = side

    @property
    def enable_put_to_light_validation(self):
        """Gets the enable_put_to_light_validation of this ConfigurePutToLightOperationBody.  # noqa: E501

        Toggle active validation for put to light.  # noqa: E501

        :return: The enable_put_to_light_validation of this ConfigurePutToLightOperationBody.  # noqa: E501
        :rtype: bool
        """
        return self._enable_put_to_light_validation

    @enable_put_to_light_validation.setter
    def enable_put_to_light_validation(self, enable_put_to_light_validation):
        """Sets the enable_put_to_light_validation of this ConfigurePutToLightOperationBody.

        Toggle active validation for put to light.  # noqa: E501

        :param enable_put_to_light_validation: The enable_put_to_light_validation of this ConfigurePutToLightOperationBody.  # noqa: E501
        :type: bool
        """

        self._enable_put_to_light_validation = enable_put_to_light_validation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigurePutToLightOperationBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigurePutToLightOperationBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
