# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnrichmentSchemaKeyRules(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'min_length': 'int',
        'max_length': 'int',
        'regex': 'str',
        'unique': 'bool'
    }

    attribute_map = {
        'min_length': 'minLength',
        'max_length': 'maxLength',
        'regex': 'regex',
        'unique': 'unique'
    }

    def __init__(self, min_length=None, max_length=None, regex=None, unique=None):  # noqa: E501
        """EnrichmentSchemaKeyRules - a model defined in Swagger"""  # noqa: E501
        self._min_length = None
        self._max_length = None
        self._regex = None
        self._unique = None
        self.discriminator = None
        if min_length is not None:
            self.min_length = min_length
        if max_length is not None:
            self.max_length = max_length
        if regex is not None:
            self.regex = regex
        if unique is not None:
            self.unique = unique

    @property
    def min_length(self):
        """Gets the min_length of this EnrichmentSchemaKeyRules.  # noqa: E501

        Minimum string length to enforce.  # noqa: E501

        :return: The min_length of this EnrichmentSchemaKeyRules.  # noqa: E501
        :rtype: int
        """
        return self._min_length

    @min_length.setter
    def min_length(self, min_length):
        """Sets the min_length of this EnrichmentSchemaKeyRules.

        Minimum string length to enforce.  # noqa: E501

        :param min_length: The min_length of this EnrichmentSchemaKeyRules.  # noqa: E501
        :type: int
        """

        self._min_length = min_length

    @property
    def max_length(self):
        """Gets the max_length of this EnrichmentSchemaKeyRules.  # noqa: E501

        Maximum string length to enforce.  # noqa: E501

        :return: The max_length of this EnrichmentSchemaKeyRules.  # noqa: E501
        :rtype: int
        """
        return self._max_length

    @max_length.setter
    def max_length(self, max_length):
        """Sets the max_length of this EnrichmentSchemaKeyRules.

        Maximum string length to enforce.  # noqa: E501

        :param max_length: The max_length of this EnrichmentSchemaKeyRules.  # noqa: E501
        :type: int
        """

        self._max_length = max_length

    @property
    def regex(self):
        """Gets the regex of this EnrichmentSchemaKeyRules.  # noqa: E501

        Regex restriction to apply to an enrichment value string.  # noqa: E501

        :return: The regex of this EnrichmentSchemaKeyRules.  # noqa: E501
        :rtype: str
        """
        return self._regex

    @regex.setter
    def regex(self, regex):
        """Sets the regex of this EnrichmentSchemaKeyRules.

        Regex restriction to apply to an enrichment value string.  # noqa: E501

        :param regex: The regex of this EnrichmentSchemaKeyRules.  # noqa: E501
        :type: str
        """

        self._regex = regex

    @property
    def unique(self):
        """Gets the unique of this EnrichmentSchemaKeyRules.  # noqa: E501

        Restrict an enrichment value to be unique in all identifiers.  # noqa: E501

        :return: The unique of this EnrichmentSchemaKeyRules.  # noqa: E501
        :rtype: bool
        """
        return self._unique

    @unique.setter
    def unique(self, unique):
        """Sets the unique of this EnrichmentSchemaKeyRules.

        Restrict an enrichment value to be unique in all identifiers.  # noqa: E501

        :param unique: The unique of this EnrichmentSchemaKeyRules.  # noqa: E501
        :type: bool
        """

        self._unique = unique

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnrichmentSchemaKeyRules, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnrichmentSchemaKeyRules):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
