# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Identifier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'code': 'str',
        'salt': 'str',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'code': 'code',
        'salt': 'salt',
        'type': 'type'
    }

    def __init__(self, id=None, code=None, salt=None, type=None):  # noqa: E501
        """Identifier - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._code = None
        self._salt = None
        self._type = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.code = code
        if salt is not None:
            self.salt = salt
        self.type = type

    @property
    def id(self):
        """Gets the id of this Identifier.  # noqa: E501


        :return: The id of this Identifier.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Identifier.


        :param id: The id of this Identifier.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def code(self):
        """Gets the code of this Identifier.  # noqa: E501

        Code of the identifier (e.g dataMatrix)  # noqa: E501

        :return: The code of this Identifier.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this Identifier.

        Code of the identifier (e.g dataMatrix)  # noqa: E501

        :param code: The code of this Identifier.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def salt(self):
        """Gets the salt of this Identifier.  # noqa: E501

        Can be either empty or any value to represent a scope of values that would result in unique values, even if provided the same code  # noqa: E501

        :return: The salt of this Identifier.  # noqa: E501
        :rtype: str
        """
        return self._salt

    @salt.setter
    def salt(self, salt):
        """Sets the salt of this Identifier.

        Can be either empty or any value to represent a scope of values that would result in unique values, even if provided the same code  # noqa: E501

        :param salt: The salt of this Identifier.  # noqa: E501
        :type: str
        """

        self._salt = salt

    @property
    def type(self):
        """Gets the type of this Identifier.  # noqa: E501

        The type of the Identifier.  # noqa: E501

        :return: The type of this Identifier.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Identifier.

        The type of the Identifier.  # noqa: E501

        :param type: The type of this Identifier.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["UNKNOWN", "CODE", "DEVICE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Identifier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Identifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
