# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class KanbanControlCycleCreateBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'number_of_cards': 'int',
        'name': 'str',
        'external_id': 'str',
        'description': 'str'
    }

    attribute_map = {
        'number_of_cards': 'numberOfCards',
        'name': 'name',
        'external_id': 'externalId',
        'description': 'description'
    }

    def __init__(self, number_of_cards=None, name=None, external_id=None, description=None):  # noqa: E501
        """KanbanControlCycleCreateBody - a model defined in Swagger"""  # noqa: E501
        self._number_of_cards = None
        self._name = None
        self._external_id = None
        self._description = None
        self.discriminator = None
        if number_of_cards is not None:
            self.number_of_cards = number_of_cards
        self.name = name
        if external_id is not None:
            self.external_id = external_id
        if description is not None:
            self.description = description

    @property
    def number_of_cards(self):
        """Gets the number_of_cards of this KanbanControlCycleCreateBody.  # noqa: E501

        Initial number of cards.  # noqa: E501

        :return: The number_of_cards of this KanbanControlCycleCreateBody.  # noqa: E501
        :rtype: int
        """
        return self._number_of_cards

    @number_of_cards.setter
    def number_of_cards(self, number_of_cards):
        """Sets the number_of_cards of this KanbanControlCycleCreateBody.

        Initial number of cards.  # noqa: E501

        :param number_of_cards: The number_of_cards of this KanbanControlCycleCreateBody.  # noqa: E501
        :type: int
        """

        self._number_of_cards = number_of_cards

    @property
    def name(self):
        """Gets the name of this KanbanControlCycleCreateBody.  # noqa: E501

        The Kanban Control Cycle's name.  # noqa: E501

        :return: The name of this KanbanControlCycleCreateBody.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KanbanControlCycleCreateBody.

        The Kanban Control Cycle's name.  # noqa: E501

        :param name: The name of this KanbanControlCycleCreateBody.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def external_id(self):
        """Gets the external_id of this KanbanControlCycleCreateBody.  # noqa: E501

        An External unique identifier to reference the Kanban Control Cycle.  # noqa: E501

        :return: The external_id of this KanbanControlCycleCreateBody.  # noqa: E501
        :rtype: str
        """
        return self._external_id

    @external_id.setter
    def external_id(self, external_id):
        """Sets the external_id of this KanbanControlCycleCreateBody.

        An External unique identifier to reference the Kanban Control Cycle.  # noqa: E501

        :param external_id: The external_id of this KanbanControlCycleCreateBody.  # noqa: E501
        :type: str
        """

        self._external_id = external_id

    @property
    def description(self):
        """Gets the description of this KanbanControlCycleCreateBody.  # noqa: E501

        The Kanban Control Cycle's description.  # noqa: E501

        :return: The description of this KanbanControlCycleCreateBody.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this KanbanControlCycleCreateBody.

        The Kanban Control Cycle's description.  # noqa: E501

        :param description: The description of this KanbanControlCycleCreateBody.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(KanbanControlCycleCreateBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, KanbanControlCycleCreateBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
