# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LanePaginatedList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'results': 'list[Lane]',
        'pagination': 'PageMetadata'
    }

    attribute_map = {
        'results': 'results',
        'pagination': 'pagination'
    }

    def __init__(self, results=None, pagination=None):  # noqa: E501
        """LanePaginatedList - a model defined in Swagger"""  # noqa: E501
        self._results = None
        self._pagination = None
        self.discriminator = None
        if results is not None:
            self.results = results
        if pagination is not None:
            self.pagination = pagination

    @property
    def results(self):
        """Gets the results of this LanePaginatedList.  # noqa: E501


        :return: The results of this LanePaginatedList.  # noqa: E501
        :rtype: list[Lane]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this LanePaginatedList.


        :param results: The results of this LanePaginatedList.  # noqa: E501
        :type: list[Lane]
        """

        self._results = results

    @property
    def pagination(self):
        """Gets the pagination of this LanePaginatedList.  # noqa: E501


        :return: The pagination of this LanePaginatedList.  # noqa: E501
        :rtype: PageMetadata
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this LanePaginatedList.


        :param pagination: The pagination of this LanePaginatedList.  # noqa: E501
        :type: PageMetadata
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LanePaginatedList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LanePaginatedList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
