# coding: utf-8

"""
    ILS API Documentation

    Neoception® Intralogistics Suite is a collection of modules for automation in the context of manufacturing.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@neoception.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LaneCarrier(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lane_id': 'str',
        'carriers': 'list[Carrier]'
    }

    attribute_map = {
        'lane_id': 'laneId',
        'carriers': 'carriers'
    }

    def __init__(self, lane_id=None, carriers=None):  # noqa: E501
        """LaneCarrier - a model defined in Swagger"""  # noqa: E501
        self._lane_id = None
        self._carriers = None
        self.discriminator = None
        if lane_id is not None:
            self.lane_id = lane_id
        if carriers is not None:
            self.carriers = carriers

    @property
    def lane_id(self):
        """Gets the lane_id of this LaneCarrier.  # noqa: E501


        :return: The lane_id of this LaneCarrier.  # noqa: E501
        :rtype: str
        """
        return self._lane_id

    @lane_id.setter
    def lane_id(self, lane_id):
        """Sets the lane_id of this LaneCarrier.


        :param lane_id: The lane_id of this LaneCarrier.  # noqa: E501
        :type: str
        """

        self._lane_id = lane_id

    @property
    def carriers(self):
        """Gets the carriers of this LaneCarrier.  # noqa: E501


        :return: The carriers of this LaneCarrier.  # noqa: E501
        :rtype: list[Carrier]
        """
        return self._carriers

    @carriers.setter
    def carriers(self, carriers):
        """Sets the carriers of this LaneCarrier.


        :param carriers: The carriers of this LaneCarrier.  # noqa: E501
        :type: list[Carrier]
        """

        self._carriers = carriers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LaneCarrier, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LaneCarrier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
